# goya config file for deep learning keras applications
date: 2021-03-12
data:
  level: 0
  size: 224
  channels: 3
  tasks:
    - Task_1
    - Task_2
    - Task_3
training:
  batch: 64
  epochs: 1
  lr: 0.001
  loss: categorical_crossentropy
  workers: 16
  pretrain: null
experiment:
  folds: 3
  split: 0.25
  seed: 42
architecture:
  hidden: 128
