# goya config file for deep learning keras applications
date: 2021-03-23
data:
  level: 0
  size: 224
  channels: 3
  tasks:
    - Task_5
training:
  batch: 16
  epochs: 100
  lr: 0.0001
  loss: categorical_crossentropy
  workers: 16
  pretrain: null
  balanced: True
  data_augmentation: True
experiment:
  folds: 1
  split: 0.20
  seed: 42
architecture:
  hidden: 128
